"""empty message

Revision ID: 13025e86cfe
Revises: None
Create Date: 2015-02-02 14:53:05.900501

"""

# revision identifiers, used by Alembic.
revision = '13025e86cfe'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sor', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sor')
    ### end Alembic commands ###
