"""empty message

Revision ID: 422db3d645f
Revises: None
Create Date: 2015-02-10 12:42:23.891489

"""

# revision identifiers, used by Alembic.
revision = '422db3d645f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sor', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #Create unique index on table sor, use column sor and key 'sig'
    op.execute("CREATE UNIQUE INDEX ON sor((sor->>'sig'))")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sor')
    ### end Alembic commands ###
