"""empty message

Revision ID: 563926d0fa4
Revises: 13025e86cfe
Create Date: 2015-02-03 14:51:35.237159

"""

# revision identifiers, used by Alembic.
revision = '563926d0fa4'
down_revision = '13025e86cfe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sor', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sor')
    ### end Alembic commands ###
