"""empty message

Revision ID: d6722d2f1
Revises: None
Create Date: 2015-02-02 11:41:26.396669

"""

# revision identifiers, used by Alembic.
revision = 'd6722d2f1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
